version: '3.7'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: lagerverwaltung
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8088:80"
    depends_on:
      - mysql


  flask:
    build: .
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql

